### ISSUE TITLE
node-gyp rebuild fails

### ISSUE THREAD

**Issue by haiqu** [cryptocoinjs/secp256k1-node#104]
Environment: Windows 7 Home Premium, nodejs v6.7.0, node-gyp v3.4.0, npm v3.10.8

Trying to build metamask-plugin and the build fails with an error that suggest a script fault in sec256k1

C:\Users\Rob\metamask-plugin\node_modules\eth-store\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Users\Rob\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "" rebuild )
'.' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to './utils/has_lib.sh gmpxx && ./utils/has_lib.sh gmp' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: gyp failed with exit code: 1
gyp ERR! stack at ChildProcess.onCpExit (C:\Users\Rob\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:191:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\Rob\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Rob\metamask-plugin\node_modules\eth-store\node_modules\secp256k1

**Comment by fanatid** [comment]
@haiqu are you checked notes for [windows](https://github.com/cryptocoinjs/secp256k1-node/tree/2a8e5fde67fb8a076a9f1781621ed88d14d8938a#windows)?

**Comment by haiqu** [comment]
Yes, all done and correct.

**Comment by Melvillian** [comment]
I'm also seeing this error while building on a Macbook v10.11

```
npm ERR! secp256k1@3.1.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.1.0 rebuild script.
npm ERR! This is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 15.6.0
npm ERR! command "/Users/alex/.nvm/versions/node/v4.1.1/bin/node" "/Users/alex/dev/BitGo/www/node_modules/.bin/npm" "run" "rebuild"
npm ERR! cwd /Users/alex/dev/BitGo/www/node_modules/secp256k1
npm ERR! node -v v4.1.1
npm ERR! npm -v 1.4.29
npm ERR! code ELIFECYCLE
```

relevant npm-debug.log info is:

```
198 silly gunzTarPerm modified mode [ 'src/privatekey.cc', 436, 420 ]
199 silly gentlyRm /Users/alex/dev/BitGo/www/node_modules/.staging/ethereumjs-util-1d88fec6/node_modules is being purged
200 verbose gentlyRm don't care about contents; nuking /Users/alex/dev/BitGo/www/node_modules/.staging/ethereumjs-util-1d88fec6/node_modules
201 silly gunzTarPerm extractEntry src/ecdh.cc
202 silly gunzTarPerm modified mode [ 'src/ecdh.cc', 436, 420 ]
203 silly gunzTarPerm extractEntry src/publickey.cc
204 silly gunzTarPerm modified mode [ 'src/publickey.cc', 436, 420 ]
205 silly gunzTarPerm extractEntry src/publickey.h
206 silly gunzTarPerm modified mode [ 'src/publickey.h', 436, 420 ]
207 silly gunzTarPerm extractEntry src/secp256k1-src/.npmignore
208 silly gunzTarPerm modified mode [ 'src/secp256k1-src/.npmignore', 436, 420 ]
209 silly gunzTarPerm extractEntry src/secp256k1-src/README.md
210 silly gunzTarPerm modified mode [ 'src/secp256k1-src/README.md', 436, 420 ]
211 silly gunzTarPerm extractEntry src/secp256k1-src/COPYING
212 silly gunzTarPerm modified mode [ 'src/secp256k1-src/COPYING', 436, 420 ]
213 silly gunzTarPerm extractEntry src/secp256k1-src/Makefile.am
214 silly gunzTarPerm modified mode [ 'src/secp256k1-src/Makefile.am', 436, 420 ]
215 silly gunzTarPerm extractEntry src/secp256k1-src/src/field_5x52_int128_impl.h
216 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/field_5x52_int128_impl.h', 436, 420 ]
217 silly gunzTarPerm extractEntry src/secp256k1-src/src/basic-config.h
218 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/basic-config.h', 436, 420 ]
219 silly gunzTarPerm extractEntry src/secp256k1-src/src/bench_ecdh.c
220 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/bench_ecdh.c', 436, 420 ]
221 silly gunzTarPerm extractEntry src/secp256k1-src/src/bench_internal.c
222 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/bench_internal.c', 436, 420 ]
223 silly gunzTarPerm extractEntry src/secp256k1-src/src/bench_recover.c
224 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/bench_recover.c', 436, 420 ]
225 silly gunzTarPerm extractEntry src/secp256k1-src/src/bench_schnorr_verify.c
226 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/bench_schnorr_verify.c', 436, 420 ]
227 silly gunzTarPerm extractEntry src/secp256k1-src/src/bench_sign.c
228 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/bench_sign.c', 436, 420 ]
229 silly gunzTarPerm extractEntry src/secp256k1-src/src/bench_verify.c
230 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/bench_verify.c', 436, 420 ]
231 silly gunzTarPerm extractEntry src/secp256k1-src/src/ecdsa.h
232 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/ecdsa.h', 436, 420 ]
233 silly gunzTarPerm extractEntry src/secp256k1-src/src/ecdsa_impl.h
234 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/ecdsa_impl.h', 436, 420 ]
235 silly gunzTarPerm extractEntry src/secp256k1-src/src/eckey.h
236 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/eckey.h', 436, 420 ]
237 silly gunzTarPerm extractEntry src/secp256k1-src/src/eckey_impl.h
238 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/eckey_impl.h', 436, 420 ]
239 silly gunzTarPerm extractEntry src/secp256k1-src/src/ecmult.h
240 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/ecmult.h', 436, 420 ]
241 silly gunzTarPerm extractEntry src/secp256k1-src/src/ecmult_const.h
242 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/ecmult_const.h', 436, 420 ]
243 silly gunzTarPerm extractEntry src/secp256k1-src/src/ecmult_const_impl.h
244 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/ecmult_const_impl.h', 436, 420 ]
245 silly gunzTarPerm extractEntry src/secp256k1-src/src/ecmult_gen.h
246 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/ecmult_gen.h', 436, 420 ]
247 silly gunzTarPerm extractEntry src/secp256k1-src/src/ecmult_gen_impl.h
248 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/ecmult_gen_impl.h', 436, 420 ]
249 silly gunzTarPerm extractEntry src/secp256k1-src/src/ecmult_impl.h
250 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/ecmult_impl.h', 436, 420 ]
251 silly gunzTarPerm extractEntry src/secp256k1-src/src/field.h
252 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/field.h', 436, 420 ]
253 silly gunzTarPerm extractEntry src/secp256k1-src/src/field_10x26.h
254 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/field_10x26.h', 436, 420 ]
255 silly gunzTarPerm extractEntry src/secp256k1-src/src/field_10x26_impl.h
256 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/field_10x26_impl.h', 436, 420 ]
257 silly gunzTarPerm extractEntry src/secp256k1-src/src/field_5x52.h
258 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/field_5x52.h', 436, 420 ]
259 silly gunzTarPerm extractEntry src/secp256k1-src/src/field_5x52_asm_impl.h
260 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/field_5x52_asm_impl.h', 436, 420 ]
261 silly gunzTarPerm extractEntry src/secp256k1-src/src/field_5x52_impl.h
262 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/field_5x52_impl.h', 436, 420 ]
263 silly gunzTarPerm extractEntry src/secp256k1-src/src/bench.h
264 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/bench.h', 436, 420 ]
265 silly gunzTarPerm extractEntry src/secp256k1-src/src/field_impl.h
266 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/field_impl.h', 436, 420 ]
267 silly gunzTarPerm extractEntry src/secp256k1-src/src/gen_context.c
268 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/gen_context.c', 436, 420 ]
269 silly gunzTarPerm extractEntry src/secp256k1-src/src/group.h
270 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/group.h', 436, 420 ]
271 silly gunzTarPerm extractEntry src/secp256k1-src/src/group_impl.h
272 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/group_impl.h', 436, 420 ]
273 silly gunzTarPerm extractEntry src/secp256k1-src/src/hash.h
274 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/hash.h', 436, 420 ]
275 silly gunzTarPerm extractEntry src/secp256k1-src/src/hash_impl.h
276 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/hash_impl.h', 436, 420 ]
277 silly gunzTarPerm extractEntry src/secp256k1-src/src/java/org/bitcoin/NativeSecp256k1.java
278 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/java/org/bitcoin/NativeSecp256k1.java',
278 silly gunzTarPerm   436,
278 silly gunzTarPerm   420 ]
279 silly gunzTarPerm extractEntry src/secp256k1-src/src/java/org_bitcoin_NativeSecp256k1.c
280 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/java/org_bitcoin_NativeSecp256k1.c',
280 silly gunzTarPerm   436,
280 silly gunzTarPerm   420 ]
281 silly gunzTarPerm extractEntry src/secp256k1-src/src/java/org_bitcoin_NativeSecp256k1.h
282 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/java/org_bitcoin_NativeSecp256k1.h',
282 silly gunzTarPerm   436,
282 silly gunzTarPerm   420 ]
283 silly gunzTarPerm extractEntry src/secp256k1-src/src/modules/ecdh/Makefile.am.include
284 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/modules/ecdh/Makefile.am.include',
284 silly gunzTarPerm   436,
284 silly gunzTarPerm   420 ]
285 silly gunzTarPerm extractEntry src/secp256k1-src/src/modules/ecdh/main_impl.h
286 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/modules/ecdh/main_impl.h', 436, 420 ]
287 silly gunzTarPerm extractEntry src/secp256k1-src/src/modules/ecdh/tests_impl.h
288 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/modules/ecdh/tests_impl.h', 436, 420 ]
289 silly gunzTarPerm extractEntry src/secp256k1-src/src/modules/recovery/Makefile.am.include
290 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/modules/recovery/Makefile.am.include',
290 silly gunzTarPerm   436,
290 silly gunzTarPerm   420 ]
291 silly gunzTarPerm extractEntry src/secp256k1-src/src/modules/recovery/main_impl.h
292 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/modules/recovery/main_impl.h',
292 silly gunzTarPerm   436,
292 silly gunzTarPerm   420 ]
293 silly gunzTarPerm extractEntry src/secp256k1-src/src/modules/recovery/tests_impl.h
294 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/modules/recovery/tests_impl.h',
294 silly gunzTarPerm   436,
294 silly gunzTarPerm   420 ]
295 silly gunzTarPerm extractEntry src/secp256k1-src/src/modules/schnorr/Makefile.am.include
296 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/modules/schnorr/Makefile.am.include',
296 silly gunzTarPerm   436,
296 silly gunzTarPerm   420 ]
297 silly gunzTarPerm extractEntry src/secp256k1-src/src/modules/schnorr/main_impl.h
298 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/modules/schnorr/main_impl.h', 436, 420 ]
299 silly gunzTarPerm extractEntry src/secp256k1-src/src/modules/schnorr/schnorr.h
300 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/modules/schnorr/schnorr.h', 436, 420 ]
301 silly gunzTarPerm extractEntry src/secp256k1-src/src/modules/schnorr/schnorr_impl.h
302 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/modules/schnorr/schnorr_impl.h',
302 silly gunzTarPerm   436,
302 silly gunzTarPerm   420 ]
303 silly gunzTarPerm extractEntry src/secp256k1-src/src/modules/schnorr/tests_impl.h
304 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/modules/schnorr/tests_impl.h',
304 silly gunzTarPerm   436,
304 silly gunzTarPerm   420 ]
305 silly gunzTarPerm extractEntry src/secp256k1-src/src/num.h
306 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/num.h', 436, 420 ]
307 silly gunzTarPerm extractEntry src/secp256k1-src/src/num_gmp.h
308 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/num_gmp.h', 436, 420 ]
309 silly gunzTarPerm extractEntry src/secp256k1-src/src/num_gmp_impl.h
310 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/num_gmp_impl.h', 436, 420 ]
311 silly gunzTarPerm extractEntry src/secp256k1-src/src/num_impl.h
312 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/num_impl.h', 436, 420 ]
313 silly gunzTarPerm extractEntry src/secp256k1-src/src/scalar.h
314 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/scalar.h', 436, 420 ]
315 silly gunzTarPerm extractEntry src/secp256k1-src/src/scalar_4x64.h
316 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/scalar_4x64.h', 436, 420 ]
317 silly gunzTarPerm extractEntry src/secp256k1-src/src/scalar_4x64_impl.h
318 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/scalar_4x64_impl.h', 436, 420 ]
319 silly gunzTarPerm extractEntry src/secp256k1-src/src/scalar_8x32.h
320 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/scalar_8x32.h', 436, 420 ]
321 silly gunzTarPerm extractEntry src/secp256k1-src/src/scalar_8x32_impl.h
322 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/scalar_8x32_impl.h', 436, 420 ]
323 silly gunzTarPerm extractEntry src/secp256k1-src/src/scalar_impl.h
324 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/scalar_impl.h', 436, 420 ]
325 silly gunzTarPerm extractEntry src/secp256k1-src/src/secp256k1.c
326 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/secp256k1.c', 436, 420 ]
327 silly gunzTarPerm extractEntry src/secp256k1-src/src/testrand.h
328 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/testrand.h', 436, 420 ]
329 silly gunzTarPerm extractEntry src/secp256k1-src/src/testrand_impl.h
330 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/testrand_impl.h', 436, 420 ]
331 silly gunzTarPerm extractEntry src/secp256k1-src/src/tests.c
332 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/tests.c', 436, 420 ]
333 silly gunzTarPerm extractEntry src/secp256k1-src/src/util.h
334 silly gunzTarPerm modified mode [ 'src/secp256k1-src/src/util.h', 436, 420 ]
335 silly gunzTarPerm extractEntry src/secp256k1-src/TODO
336 silly gunzTarPerm modified mode [ 'src/secp256k1-src/TODO', 436, 420 ]
337 silly gunzTarPerm extractEntry src/secp256k1-src/autogen.sh
338 silly gunzTarPerm modified mode [ 'src/secp256k1-src/autogen.sh', 509, 493 ]
339 silly gunzTarPerm extractEntry src/secp256k1-src/.travis.yml
340 silly gunzTarPerm modified mode [ 'src/secp256k1-src/.travis.yml', 436, 420 ]
341 silly gunzTarPerm extractEntry src/secp256k1-src/configure.ac
342 silly gunzTarPerm modified mode [ 'src/secp256k1-src/configure.ac', 436, 420 ]
343 silly gunzTarPerm extractEntry src/secp256k1-src/contrib/lax_der_parsing.c
344 silly gunzTarPerm modified mode [ 'src/secp256k1-src/contrib/lax_der_parsing.c', 436, 420 ]
345 silly gunzTarPerm extractEntry src/secp256k1-src/contrib/lax_der_parsing.h
346 silly gunzTarPerm modified mode [ 'src/secp256k1-src/contrib/lax_der_parsing.h', 436, 420 ]
347 silly gunzTarPerm extractEntry src/secp256k1-src/contrib/lax_der_privatekey_parsing.c
348 silly gunzTarPerm modified mode [ 'src/secp256k1-src/contrib/lax_der_privatekey_parsing.c',
348 silly gunzTarPerm   436,
348 silly gunzTarPerm   420 ]
349 silly gunzTarPerm extractEntry src/secp256k1-src/contrib/lax_der_privatekey_parsing.h
350 silly gunzTarPerm modified mode [ 'src/secp256k1-src/contrib/lax_der_privatekey_parsing.h',
350 silly gunzTarPerm   436,
350 silly gunzTarPerm   420 ]
351 silly gunzTarPerm extractEntry src/secp256k1-src/include/secp256k1.h
352 silly gunzTarPerm modified mode [ 'src/secp256k1-src/include/secp256k1.h', 436, 420 ]
353 silly gunzTarPerm extractEntry src/secp256k1-src/include/secp256k1_ecdh.h
354 silly gunzTarPerm modified mode [ 'src/secp256k1-src/include/secp256k1_ecdh.h', 436, 420 ]
355 silly gunzTarPerm extractEntry src/secp256k1-src/include/secp256k1_recovery.h
356 silly gunzTarPerm modified mode [ 'src/secp256k1-src/include/secp256k1_recovery.h', 436, 420 ]
357 silly gunzTarPerm extractEntry src/secp256k1-src/include/secp256k1_schnorr.h
358 silly gunzTarPerm modified mode [ 'src/secp256k1-src/include/secp256k1_schnorr.h', 436, 420 ]
359 silly gunzTarPerm extractEntry src/secp256k1-src/libsecp256k1.pc.in
360 silly gunzTarPerm modified mode [ 'src/secp256k1-src/libsecp256k1.pc.in', 436, 420 ]
361 silly gunzTarPerm extractEntry src/secp256k1-src/obj/.npmignore
362 silly gunzTarPerm modified mode [ 'src/secp256k1-src/obj/.npmignore', 436, 420 ]
363 silly gunzTarPerm extractEntry src/secp256k1-src/sage/group_prover.sage
364 silly gunzTarPerm modified mode [ 'src/secp256k1-src/sage/group_prover.sage', 436, 420 ]
365 silly gunzTarPerm extractEntry src/secp256k1-src/sage/secp256k1.sage
366 silly gunzTarPerm modified mode [ 'src/secp256k1-src/sage/secp256k1.sage', 436, 420 ]
367 silly gunzTarPerm extractEntry src/secp256k1-src/sage/weierstrass_prover.sage
368 silly gunzTarPerm modified mode [ 'src/secp256k1-src/sage/weierstrass_prover.sage', 436, 420 ]
369 silly gunzTarPerm extractEntry src/signature.cc
370 silly gunzTarPerm modified mode [ 'src/signature.cc', 436, 420 ]
371 silly gunzTarPerm extractEntry src/signature.h
372 silly gunzTarPerm modified mode [ 'src/signature.h', 436, 420 ]
373 silly gunzTarPerm extractEntry src/util.h
374 silly gunzTarPerm modified mode [ 'src/util.h', 436, 420 ]
375 silly gunzTarPerm extractEntry utils/has_lib.sh
376 silly gunzTarPerm modified mode [ 'utils/has_lib.sh', 509, 493 ]
377 silly gentlyRm /Users/alex/dev/BitGo/www/node_modules/.staging/secp256k1-14720f67/node_modules is being purged
378 verbose gentlyRm don't care about contents; nuking /Users/alex/dev/BitGo/www/node_modules/.staging/secp256k1-14720f67/node_modules
379 silly doParallel preinstall 2
380 silly preinstall secp256k1@3.1.0 /Users/alex/dev/BitGo/www/node_modules/.staging/secp256k1-14720f67
381 info lifecycle secp256k1@3.1.0~preinstall: secp256k1@3.1.0
382 silly preinstall ethereumjs-util@4.4.0 /Users/alex/dev/BitGo/www/node_modules/.staging/ethereumjs-util-1d88fec6
383 info lifecycle ethereumjs-util@4.4.0~preinstall: ethereumjs-util@4.4.0
384 silly lifecycle secp256k1@3.1.0~preinstall: no script for preinstall, continuing
385 silly lifecycle ethereumjs-util@4.4.0~preinstall: no script for preinstall, continuing
386 silly doReverseSerial remove 0
387 silly doSerial move 0
388 silly doSerial finalize 2
389 silly finalize /Users/alex/dev/BitGo/www/node_modules/secp256k1
390 silly finalize /Users/alex/dev/BitGo/www/node_modules/ethereumjs-util
391 silly doSerial build 2
392 silly build secp256k1@3.1.0
393 info linkStuff secp256k1@3.1.0
394 silly linkStuff secp256k1@3.1.0 has /Users/alex/dev/BitGo/www/node_modules as its parent node_modules
395 verbose linkBins secp256k1@3.1.0
396 verbose linkMans secp256k1@3.1.0
397 silly build ethereumjs-util@4.4.0
398 info linkStuff ethereumjs-util@4.4.0
399 silly linkStuff ethereumjs-util@4.4.0 has /Users/alex/dev/BitGo/www/node_modules as its parent node_modules
400 verbose linkBins ethereumjs-util@4.4.0
401 verbose linkMans ethereumjs-util@4.4.0
402 silly doSerial global-link 0
403 silly doParallel update-linked 0
404 silly doSerial install 2
405 silly install secp256k1@3.1.0 /Users/alex/dev/BitGo/www/node_modules/.staging/secp256k1-14720f67
406 info lifecycle secp256k1@3.1.0~install: secp256k1@3.1.0
407 verbose lifecycle secp256k1@3.1.0~install: unsafe-perm in lifecycle true
408 verbose lifecycle secp256k1@3.1.0~install: PATH: /Users/alex/.nvm/versions/node/v4.1.1/lib/node_modules/npm/bin/node-gyp-bin:/Users/alex/dev/BitGo/www/node_modules/secp256k1/node_modules/.bin:/Users/alex/dev/BitGo/www/node_modules/.bin:/Users/alex/.nvm/versions/node/v4.1.1/bin:/Users/alex/.yarn/bin:/usr/local/Cellar/pyenv-virtualenv/20160202/shims:/usr/local/Cellar/pyenv/20160310/libexec:/Users/alex/.pyenv/shims:/Users/alex/.nvm/versions/node/v4.1.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/alex/PhabricatorFiles/arcanist/bin:/Users/alex/mavens/apache-maven-3.2.5/bin:/Users/alex/dev/gopath/bin:/Users/alex/dev/bitgo-scripts
409 verbose lifecycle secp256k1@3.1.0~install: CWD: /Users/alex/dev/BitGo/www/node_modules/secp256k1
410 silly lifecycle secp256k1@3.1.0~install: Args: [ '-c', 'npm run rebuild' ]
411 silly lifecycle secp256k1@3.1.0~install: Returned: code: 1  signal: null
412 info lifecycle secp256k1@3.1.0~install: Failed to exec install script
413 verbose unlock done using /Users/alex/.npm/_locks/staging-75198ae7e9b62b36.lock for /Users/alex/dev/BitGo/www/node_modules/.staging
414 silly rollbackFailedOptional Starting
415 silly rollbackFailedOptional Finishing
416 silly runTopLevelLifecycles Starting
417 silly runTopLevelLifecycles Finishing
418 silly install printInstalled
419 verbose stack Error: secp256k1@3.1.0 install: `npm run rebuild`
419 verbose stack Exit status 1
419 verbose stack     at EventEmitter.<anonymous> (/Users/alex/.nvm/versions/node/v4.1.1/lib/node_modules/npm/lib/utils/lifecycle.js:244:16)
419 verbose stack     at emitTwo (events.js:87:13)
419 verbose stack     at EventEmitter.emit (events.js:172:7)
419 verbose stack     at ChildProcess.<anonymous> (/Users/alex/.nvm/versions/node/v4.1.1/lib/node_modules/npm/lib/utils/spawn.js:24:14)
419 verbose stack     at emitTwo (events.js:87:13)
419 verbose stack     at ChildProcess.emit (events.js:172:7)
419 verbose stack     at maybeClose (internal/child_process.js:817:16)
419 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
420 verbose pkgid secp256k1@3.1.0
421 verbose cwd /Users/alex/dev/BitGo/www
422 error Darwin 15.6.0
423 error argv "/Users/alex/.nvm/versions/node/v4.1.1/bin/node" "/Users/alex/.nvm/versions/node/v4.1.1/bin/npm" "install"
424 error node v4.1.1
425 error npm  v3.8.8
426 error code ELIFECYCLE
427 error secp256k1@3.1.0 install: `npm run rebuild`
427 error Exit status 1
428 error Failed at the secp256k1@3.1.0 install script 'npm run rebuild'.
428 error Make sure you have the latest version of node.js and npm installed.
428 error If you do, this is most likely a problem with the secp256k1 package,
428 error not with npm itself.
428 error Tell the author that this fails on your system:
428 error     npm run rebuild
428 error You can get information on how to open an issue for this project with:
428 error     npm bugs secp256k1
428 error Or if that isn't available, you can get their info via:
428 error     npm owner ls secp256k1
428 error There is likely additional logging output above.
429 verbose exit [ 1, true ]
```

**Comment by fanatid** [comment]
Prebuild binaries added, now all should be installed without build tools.
