### ISSUE TITLE
'npm run rebuild' script fails while npm installing secp256k1

### ISSUE THREAD

**Issue by Melvillian** [cryptocoinjs/secp256k1-node#105]
I have `"secp256k1": "3.1.0"` listed as a direct dependency in by `package.json` file. When I run `npm install` I get all of my packages installed except for `secp256k1`, which fails with the following error outputted to stdout:

```
npm WARN In npm@1.4.29 replacing bundled version of readable-stream with readable-stream@1.0.34
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/alex/.nvm/versions/node/v4.1.1/bin/node" "/Users/alex/.nvm/versions/node/v4.1.1/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v3.8.8
npm ERR! code ELIFECYCLE

npm ERR! secp256k1@3.1.0 install: `npm run rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.1.0 install script 'npm run rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/alex/dev/BitGo/www/npm-debug.log
```

note that the `npm-debug.log` file is empty.

**Comment by Melvillian** [comment]
On more testing, I think the problem lies with the node-gyp script using package-local version of npm rather than the global version

**Comment by Melvillian** [comment]
A little more detail:

```
gyp: /Users/alex/.node-gyp/4.1.1/common.gypi not found (cwd: /Users/alex/dev/BitGo/www/node_modules/secp256k1) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/alex/dev/BitGo/www/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/alex/.nvm/versions/node/v4.1.1/bin/node" "/Users/alex/dev/BitGo/www/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/alex/dev/BitGo/www/node_modules/secp256k1
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
```

**Comment by fanatid** [comment]
Prebuild binaries added, now all should be installed without build tools.
