### ISSUE TITLE
When I try to install it on Windows I get a lot of errors and warnings

### ISSUE THREAD

**Issue by pupeno** [cryptocoinjs/secp256k1-node#111]
I still don't know how much of a problem this is, did I get a working install or not? but I do get lot's of errors and warnings:

```
npm install secp256k1

> secp256k1@2.0.10 install C:\Users\pupeno\Documents\projectx\node_modules\eccrypto\node_modules\secp256k1
> npm run rebuild


> secp256k1@2.0.10 rebuild C:\Users\pupeno\Documents\projectx\node_modules\eccrypto\node_modules\secp256k1
> node-gyp rebuild


C:\Users\pupeno\Documents\projectx\node_modules\eccrypto\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
'.' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to './utils/has_lib.sh gmpxx && ./utils/has_lib.sh gmp' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\pupeno\Documents\projectx\node_modules\eccrypto\node_modules\secp256k1
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@2.0.10 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@2.0.10 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\pupeno\Documents\projectx\node_modules\eccrypto\node_modules\secp256k1\npm-debug.log

> secp256k1@3.2.5 install C:\Users\pupeno\Documents\projectx\node_modules\secp256k1
> prebuild-install || node-gyp rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

prebuild-install info begin Prebuild-install version 2.1.0
prebuild-install info looking for local prebuild @ prebuilds\secp256k1-v3.2.5-node-v48-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\pupeno\AppData\Roaming\npm-cache\_prebuilds\https-github.com-cryptocoinjs-secp256k1-node-releases-download-v3.2.5-secp256k1-v3.2.5-node-v48-win32-x64.tar.gz
prebuild-install http request GET https://github.com/cryptocoinjs/secp256k1-node/releases/download/v3.2.5/secp256k1-v3.2.5-node-v48-win32-x64.tar.gz
prebuild-install http 200 https://github.com/cryptocoinjs/secp256k1-node/releases/download/v3.2.5/secp256k1-v3.2.5-node-v48-win32-x64.tar.gz
prebuild-install info downloading to @ C:\Users\pupeno\AppData\Roaming\npm-cache\_prebuilds\https-github.com-cryptocoinjs-secp256k1-node-releases-download-v3.2.5-secp256k1-v3.2.5-node-v48-win32-x64.tar.gz.12612-d79f7924c21f2.tmp
prebuild-install info renaming to @ C:\Users\pupeno\AppData\Roaming\npm-cache\_prebuilds\https-github.com-cryptocoinjs-secp256k1-node-releases-download-v3.2.5-secp256k1-v3.2.5-node-v48-win32-x64.tar.gz
prebuild-install info unpacking @ C:\Users\pupeno\AppData\Roaming\npm-cache\_prebuilds\https-github.com-cryptocoinjs-secp256k1-node-releases-download-v3.2.5-secp256k1-v3.2.5-node-v48-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\pupeno\Documents\projectx\node_modules\secp256k1\build\Release\secp256k1.node
prebuild-install info unpack required C:\Users\pupeno\Documents\projectx\node_modules\secp256k1\build\Release\secp256k1.node successfully
prebuild-install info install Prebuild successfully installed!
projectx@0.0.0 C:\Users\pupeno\Documents\projectx
`-- secp256k1@3.2.5
  +-- bindings@1.2.1
  +-- bip66@1.1.4
  +-- create-hash@1.1.2
  | +-- cipher-base@1.0.3
  | +-- ripemd160@1.0.1
  | `-- sha.js@2.4.8
  +-- drbg.js@1.0.1
  | +-- browserify-aes@1.0.6
  | | +-- buffer-xor@1.0.3
  | | `-- evp_bytestokey@1.0.0
  | `-- create-hmac@1.1.4
  `-- prebuild-install@2.1.0
    +-- expand-template@1.0.3
    +-- github-from-package@0.0.0
    +-- minimist@1.2.0
    +-- node-abi@1.0.3
    +-- noop-logger@0.1.1
    +-- pump@1.0.2
    | `-- end-of-stream@1.1.0
    |   `-- once@1.3.3
    +-- simple-get@1.4.3
    | +-- unzip-response@1.0.2
    | `-- xtend@4.0.1
    +-- tar-fs@1.15.0
    | `-- tar-stream@1.5.2
    |   +-- bl@1.2.0
    |   | `-- readable-stream@2.2.2
    |   |   `-- isarray@1.0.0
    |   +-- readable-stream@2.2.2
    |   | `-- isarray@1.0.0
    |   `-- xtend@4.0.1
    `-- xtend@4.0.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: secp256k1@2.0.10 (node_modules\eccrypto\node_modules\secp256k1):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: secp256k1@2.0.10 install: `npm run rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

```

**Comment by fanatid** [comment]
Hey @pupeno 
secp256k1@3.2.5 is installed with prebuild binaries
secp256k1@2.1.0 is not installed (dependency of `eccrypto`), I hope that [this section](https://github.com/cryptocoinjs/secp256k1-node/tree/fbfc19e7ca63fa3a2ecab7d8c9a4516c78235d7f#windows) will be helpful
