### ISSUE TITLE
Cannot build on windows

### ISSUE THREAD

**Issue by blurHY** [cryptocoinjs/secp256k1-node#151]
```
> integer@2.1.0 install D:\IPZN\node_modules\integer
> node-gyp rebuild


D:\IPZN\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Users\blurHY\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\blurHY\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  integer.cpp
  win_delay_load_hook.cc
d:\ipzn\node_modules\integer\src\integer.cpp(370): warning C4804: “-”: 在操作中使用类型“bool”不安全 [D:\IPZN\node_modules\integer\build\integer.vcxproj]
    正在创建库 D:\IPZN\node_modules\integer\build\Release\integer.lib 和对象 D:\IPZN\node_modules\integer\build\Release\integer.exp
  正在生成代码
  All 265 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  已完成代码的生成
  integer.vcxproj -> D:\IPZN\node_modules\integer\build\Release\\integer.node
  Copying D:\IPZN\node_modules\integer\build\Release\/integer.node to build\integer.node
  已复制         1 个文件。

> secp256k1@2.0.4 install D:\IPZN\node_modules\eth-crypto\node_modules\eccrypto\node_modules\secp256k1
> npm run rebuild


> secp256k1@2.0.4 rebuild D:\IPZN\node_modules\eth-crypto\node_modules\eccrypto\node_modules\secp256k1
> node-gyp rebuild


D:\IPZN\node_modules\eth-crypto\node_modules\eccrypto\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Users\blurHY\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\blurHY\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
gyp: Call to './utils/has_lib.sh gmpxx && ./utils/has_lib.sh gmp' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\blurHY\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:323:16)
gyp ERR! stack     at ChildProcess.emit (events.js:197:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\blurHY\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\IPZN\node_modules\eth-crypto\node_modules\eccrypto\node_modules\secp256k1
gyp ERR! node -v v11.9.0
gyp ERR! node-gyp -v v5.0.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@2.0.4 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@2.0.4 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\blurHY\AppData\Roaming\npm-cache\_logs\2019-07-22T10_13_21_138Z-debug.log

> keccak@1.4.0 install D:\IPZN\node_modules\keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@1.4.0 rebuild D:\IPZN\node_modules\keccak
> node-gyp rebuild


D:\IPZN\node_modules\keccak>if not defined npm_config_node_gyp (node "C:\Users\blurHY\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\blurHY\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  addon.cc
  win_delay_load_hook.cc
d:\ipzn\node_modules\nan\nan.h(1064): warning C4996: 'v8::Value::ToString': 被声明为已否决 (编译源文件 ..\src\addon.cc) [D:\IPZN\node_modules\keccak\build\keccak.vcxproj]
  c:\users\blurhy\appdata\local\node-gyp\cache\11.9.0\include\node\v8.h(2537): note: 参见“v8::Value::ToString”的声明 (编译源文件 ..\src\addon.cc)
d:\ipzn\node_modules\keccak\src\libkeccak\keccaksponge.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失 (编译源文件 ..\src\addon.cc) [D:\IPZN\node_modules\keccak\build\keccak.vcxproj]
d:\ipzn\node_modules\keccak\src\addon.cc(37): warning C4996: 'v8::Value::IntegerValue': 被声明为已否决 [D:\IPZN\node_modules\keccak\build\keccak.vcxproj]
  c:\users\blurhy\appdata\local\node-gyp\cache\11.9.0\include\node\v8.h(2570): note: 参见“v8::Value::IntegerValue”的声明
d:\ipzn\node_modules\keccak\src\addon.cc(38): warning C4996: 'v8::Value::IntegerValue': 被声明为已否决 [D:\IPZN\node_modules\keccak\build\keccak.vcxproj]
  c:\users\blurhy\appdata\local\node-gyp\cache\11.9.0\include\node\v8.h(2570): note: 参见“v8::Value::IntegerValue”的声明
d:\ipzn\node_modules\keccak\src\addon.cc(56): warning C4996: 'v8::Value::IntegerValue': 被声明为已否决 [D:\IPZN\node_modules\keccak\build\keccak.vcxproj]
  c:\users\blurhy\appdata\local\node-gyp\cache\11.9.0\include\node\v8.h(2570): note: 参见“v8::Value::IntegerValue”的声明
d:\ipzn\node_modules\keccak\src\addon.cc(64): warning C4996: 'v8::Value::IntegerValue': 被声明为已否决 [D:\IPZN\node_modules\keccak\build\keccak.vcxproj]
  c:\users\blurhy\appdata\local\node-gyp\cache\11.9.0\include\node\v8.h(2570): note: 参见“v8::Value::IntegerValue”的声明
d:\ipzn\node_modules\keccak\src\addon.cc(75): warning C4996: 'v8::Value::ToObject': 被声明为已否决 [D:\IPZN\node_modules\keccak\build\keccak.vcxproj]
  c:\users\blurhy\appdata\local\node-gyp\cache\11.9.0\include\node\v8.h(10254): note: 参见“v8::Value::ToObject”的声明
  KeccakSponge.c
  KeccakP-1600-reference.c
d:\ipzn\node_modules\keccak\src\libkeccak\keccaksponge.h : warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失 (编译源文件 ..\src\libkeccak\KeccakSponge.c) [D:\IPZN\node_modules\keccak\build\keccak.vcxproj]
    正在创建库 D:\IPZN\node_modules\keccak\build\Release\keccak.lib 和对象 D:\IPZN\node_modules\keccak\build\Release\keccak.exp
  正在生成代码
  All 156 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  已完成代码的生成
  keccak.vcxproj -> D:\IPZN\node_modules\keccak\build\Release\\keccak.node

> secp256k1@3.7.0 install D:\IPZN\node_modules\secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.7.0 rebuild D:\IPZN\node_modules\secp256k1
> node-gyp rebuild


D:\IPZN\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Users\blurHY\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\blurHY\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
  addon.cc
  privatekey.cc
  publickey.cc
  signature.cc
  ecdsa.cc
  ecdh.cc
  win_delay_load_hook.cc
d:\ipzn\node_modules\secp256k1\src\secp256k1-src\src\scalar_8x32_impl.h(198): warning C4319: “~”: 将“const uint32_t”扩展到更大的“uint64_t”时为零 (编译源文件 ..\src\privatekey.cc) [D:\IPZN\node_modules\secp256k1\build\secp256k1.vcxproj]
d:\ipzn\node_modules\secp256k1\src\secp256k1-src\src\scalar_8x32_impl.h(200): warning C4319: “~”: 将“const uint32_t”扩展到更大的“uint64_t”时为零 (编译源文件 ..\src\privatekey.cc) [D:\IPZN\node_modules\secp256k1\build\secp256k1.vcxproj]
d:\ipzn\node_modules\secp256k1\src\secp256k1-src\src\scalar_8x32_impl.h(202): warning C4319: “~”: 将“const uint32_t”扩展到更大的“uint64_t”时为零 (编译源文件 ..\src\privatekey.cc) [D:\IPZN\node_modules\secp256k1\build\secp256k1.vcxproj]
d:\ipzn\node_modules\secp256k1\src\secp256k1-src\src\scalar_8x32_impl.h(204): warning C4319: “~”: 将“const uint32_t”扩展到更大的“uint64_t”时为零 (编译源文件 ..\src\privatekey.cc) [D:\IPZN\node_modules\secp256k1\build\secp256k1.vcxproj]
d:\ipzn\node_modules\secp256k1\src\secp256k1-src\src\scalar_8x32_impl.h(206): warning C4319: “~”: 将“const uint32_t”扩展到更大的“uint64_t”时为零 (编译源文件 ..\src\privatekey.cc) [D:\IPZN\node_modules\secp256k1\build\secp256k1.vcxproj]
d:\ipzn\node_modules\secp256k1\src\secp256k1-src\src\scalar_8x32_impl.h(208): warning C4319: “~”: 将“const uint32_t”扩展到更大的“uint64_t”时为零 (编译源文件 ..\src\privatekey.cc) [D:\IPZN\node_modules\secp256k1\build\secp256k1.vcxproj]
d:\ipzn\node_modules\secp256k1\src\secp256k1-src\src\scalar_8x32_impl.h(210): warning C4319: “~”: 将“const uint32_t”扩展到更大的“uint64_t”时为零 (编译源文件 ..\src\privatekey.cc) [D:\IPZN\node_modules\secp256k1\build\secp256k1.vcxproj]
d:\ipzn\node_modules\secp256k1\src\secp256k1-src\src\scalar_8x32_impl.h(212): warning C4319: “~”: 将“const uint32_t”扩展到更大的“uint64_t”时为零 (编译源文件 ..\src\privatekey.cc) [D:\IPZN\node_modules\secp256k1\build\secp256k1.vcxproj]
  secp256k1.c
  lax_der_parsing.c
  lax_der_privatekey_parsing.c
    正在创建库 D:\IPZN\node_modules\secp256k1\build\Release\secp256k1.lib 和对象 D:\IPZN\node_modules\secp256k1\build\Release\secp256k1.exp
  正在生成代码
正在尝试取消生成...
```

I tried https://github.com/cryptocoinjs/secp256k1-node/issues/111, but it's not working

**Comment by blurHY** [comment]
The same as https://github.com/cryptocoinjs/secp256k1-node/issues/111
```
 else (node "" rebuild )
'.' is not recognized as an internal or external command,
```

**Comment by junderw** [comment]
Try using bash?

**Comment by blurHY** [comment]
Nope, I have to make it usable on Windows, not only WSL

---

Can I use It for encrypting by privatekey ? I wnat to sign something, but I want to use multihash for hashing.
I can't find any API on that

**Comment by junderw** [comment]
> I have to make it usable on Windows

MinGW is usable on windows... you don't need WSL.

http://www.mingw.org/wiki/MSYS

**Comment by blurHY** [comment]
> > I have to make it usable on Windows
> 
> MinGW is usable on windows... you don't need WSL.
> 
> http://www.mingw.org/wiki/MSYS

umm, yeah, but how ?

**Comment by junderw** [comment]
> umm, yeah, but how ?

I don't have a windows machine to test it on, but back when I was a newb programmer using Windows I remember using MinGW as a bash substitute (we didn't have WSL back in the day)

After pouring over many threads of node-gyp and Windows compatibility issues it seems that no one can ever figure it out.

So the best I can say is follow the instructions on node-gyp's repo.

https://github.com/nodejs/node-gyp#on-windows

Also, since your production server is 99.999% likely going to be Linux... it would probably be best to build on the same environment. If you use Windows servers... then maybe Microsoft support might be able to help you?

I hope you find the solution to your problem.

**Comment by blurHY** [comment]
I am writing an application for users, so , unfortunately I have make it compatible to windows.
Well, how to sign something with ecc and multiformats/multihash ?

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
