### ISSUE TITLE
'npm install secp256k1' failing on arch linux

### ISSUE THREAD

**Issue by hackergrrl** [cryptocoinjs/secp256k1-node#16]
```
[stephen:~]$ npm install secp256k1
-
> secp256k1@0.0.15 install /home/stephen/node_modules/secp256k1
> node-gyp rebuild

gyp: Call to './utils/has_lib.sh gmpxx' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.17.4-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/stephen/node_modules/secp256k1
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.17.4-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "secp256k1"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! secp256k1@0.0.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@0.0.15 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.
```

**Comment by wanderer** [comment]
hmm can you tell me what happens when you just run the `has_lib.sh` script? To do this run the following  
`git clone https://github.com/wanderer/secp256k1-node`  
`cd secp256k1-node`  
`./utils/has_lib.sh gmpxx`

**Comment by hackergrrl** [comment]
I'm getting `true`.

**Comment by wanderer** [comment]
thanks @noffle ! I'm runnig on arch as well but I can't reproduce yet.  Can you try building it from your cloned directory? `npm install .`.

**Comment by wanderer** [comment]
oh also do `ls /usr/include/ | grep gmp` and see if you have gmpxx.h

**Comment by hackergrrl** [comment]
Hey! Sorry it took so long for me to get back to you. Here are the results:

```
[stephen:/tmp/secp256k1-node]$ npm install .
-
> secp256k1@0.0.15 install /tmp/secp256k1-node
> node-gyp rebuild

gyp: Call to './utils/has_lib.sh gmpxx' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.17.4-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/secp256k1-node
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

npm ERR! Linux 3.17.4-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "."
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@0.0.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@0.0.15 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/secp256k1-node/npm-debug.log
```

and

```
[stephen:/tmp/secp256k1-node]$ ls /usr/include | grep gmp
gmp.h
gmpxx.h
```

**Comment by dsri** [comment]
Try upgrading node - secp256k1\* is only supported in node 0.11/0.12 (not 0.10)

**Comment by wanderer** [comment]
@dsri im not sure what ECDH has to do with this issue, but yes your right secp256k1 doesn't support 0.10 anymore

**Comment by dsri** [comment]
Updated, thanks. I was on 0.10 and had the same issue earlier, but upgrading fixed it

**Comment by wanderer** [comment]
@noffle im going to close this becuase I think node version .10 is totally broken, But please reopen if it still doesn't work on a later version

**Comment by kumavis** [comment]
getting this on OSX after upgrading npm:

```
gyp: Call to './utils/has_lib.sh gmpxx' returned exit status 0. while trying to load binding.gyp
```

**Comment by wanderer** [comment]
@noffle @kumavis has it working on the v 1.1.4

**Comment by kumavis** [comment]
thanks :+1:
