### ISSUE TITLE
Failing to "npm-install" on OSX

### ISSUE THREAD

**Issue by jesuscript** [cryptocoinjs/secp256k1-node#3]
```
$ npm install
\
> secp256k1@0.0.7 install /Users/megatv/CODE/secp256k1-node
> node-gyp rebuild

  CXX(target) Release/obj.target/secp256k1/secp256k1.o
../secp256k1.cc:13:43: warning: field 'pk' will be initialized after field 'msg_len'
      [-Wreorder]
    : NanAsyncWorker(callback), msg(msg), pk(pk), msg_len(msg_len), nonce(nonce), ...
                                          ^
../secp256k1.cc:13:69: warning: field 'nonce' will be initialized after field 'sig_len'
      [-Wreorder]
    : NanAsyncWorker(callback), msg(msg), pk(pk), msg_len(msg_len), nonce(nonce), ...
                                                                    ^
../secp256k1.cc:71:61: warning: field 'sig' will be initialized after field 'compressed'
      [-Wreorder]
    : NanAsyncWorker(callback), msg(msg), msg_len(msg_len), sig(sig), compressed(c...
                                                            ^
../secp256k1.cc:71:71: warning: field 'compressed' will be initialized after field
      'rec_id' [-Wreorder]
    : NanAsyncWorker(callback), msg(msg), msg_len(msg_len), sig(sig), compressed(c...
                                                                      ^
../secp256k1.cc:205:7: warning: unused variable 'result' [-Wunused-variable]
  int result = secp256k1_ecdsa_sign(msg_data, msg_len , sig , &sig_len, pk_data, n...
      ^
../secp256k1.cc:448:7: warning: unused variable 'results' [-Wunused-variable]
  int results = secp256k1_ecdsa_pubkey_decompress(pk_data, &pk_len);
      ^
../secp256k1.cc:464:7: warning: unused variable 'results' [-Wunused-variable]
  int results = secp256k1_ecdsa_privkey_import(sec_key, pk_data, pk_len);
      ^
../secp256k1.cc:464:48: warning: variable 'sec_key' is uninitialized when used here
      [-Wuninitialized]
  int results = secp256k1_ecdsa_privkey_import(sec_key, pk_data, pk_len);
                                               ^~~~~~~
../secp256k1.cc:463:25: note: initialize the variable 'sec_key' to silence this warning
  unsigned char *sec_key;
                        ^
                         = NULL
../secp256k1.cc:481:7: warning: unused variable 'results' [-Wunused-variable]
  int results = secp256k1_ecdsa_privkey_export(sk_data, privKey, &pk_len, compressed);
      ^
../secp256k1.cc:481:57: warning: variable 'privKey' is uninitialized when used here
      [-Wuninitialized]
  int results = secp256k1_ecdsa_privkey_export(sk_data, privKey, &pk_len, compressed);
                                                        ^~~~~~~
../secp256k1.cc:479:25: note: initialize the variable 'privKey' to silence this warning
  unsigned char *privKey;
                        ^
                         = NULL
../secp256k1.cc:496:7: warning: unused variable 'results' [-Wunused-variable]
  int results = secp256k1_ecdsa_privkey_tweak_add(sk, tweak);
      ^
../secp256k1.cc:511:7: warning: unused variable 'results' [-Wunused-variable]
  int results = secp256k1_ecdsa_privkey_tweak_mul(sk, tweak);
      ^
../secp256k1.cc:527:7: warning: unused variable 'results' [-Wunused-variable]
  int results = secp256k1_ecdsa_pubkey_tweak_add(pk, pk_len, tweak);
      ^
../secp256k1.cc:543:7: warning: unused variable 'results' [-Wunused-variable]
  int results = secp256k1_ecdsa_pubkey_tweak_mul(pk, pk_len, tweak);
      ^
In file included from ../secp256k1.cc:1:
../node_modules/nan/nan.h:1080:12: error: no viable conversion from 'Handle<v8::Boolean>'
      to 'v8::Local<Boolean>'
    return T::New(arg);
           ^~~~~~~~~~~
../secp256k1.cc:347:20: note: in instantiation of function template specialization
      'NanNew<v8::Boolean, int>' requested here
    NanReturnValue(NanNew<Boolean>(0));
                   ^
../node_modules/nan/nan.h:1335:51: note: expanded from macro 'NanReturnValue'
# define NanReturnValue(value) return scope.Close(value)
                                                  ^
/Users/megatv/.node-gyp/0.10.33/deps/v8/include/v8.h:269:26: note: candidate constructor
      (the implicit copy constructor) not viable: cannot bind base class object of type
      'Handle<v8::Boolean>' to derived class reference 'const v8::Local<v8::Boolean> &'
      for 1st argument
template <class T> class Local : public Handle<T> {
                         ^
/Users/megatv/.node-gyp/0.10.33/deps/v8/include/v8.h:272:29: note: candidate template
      ignored: could not match 'Local' against 'Handle'
  template <class S> inline Local(Local<S> that)
                            ^
/Users/megatv/.node-gyp/0.10.33/deps/v8/include/v8.h:281:29: note: candidate template
      ignored: could not match 'S *' against 'Handle<v8::Boolean>'
  template <class S> inline Local(S* that) : Handle<T>(that) { }
                            ^
14 warnings and 1 error generated.
make: *** [Release/obj.target/secp256k1/secp256k1.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/megatv/CODE/secp256k1-node
gyp ERR! node -v v0.10.33
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.6
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@0.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@0.0.7 install script.
npm ERR! This is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/megatv/CODE/secp256k1-node/npm-debug.log
```

Node version: 0.10.33
npm version: 2.1.6
OSX version: 10.10

**Comment by wanderer** [comment]
just push 0.8. It should be fixed now!

**Comment by jesuscript** [comment]
yup, 0.0.8 builds fine. Thank you
