### ISSUE TITLE
fatal error: secp256k1.h: No such file or directory

### ISSUE THREAD

**Issue by Kagami** [cryptocoinjs/secp256k1-node#43]
Hi. I can't install latest version of `secp256k1-node` from npm. npm output:

```
$ npm i secp256k1
-
> secp256k1@2.0.0 install /home/user/code/tmp/node/ecc/node_modules/secp256k1
> npm run rebuild


> secp256k1@2.0.0 rebuild /home/user/code/tmp/node/ecc/node_modules/secp256k1
> node-gyp rebuild

make: Entering directory '/home/user/code/tmp/node/ecc/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/src/addon.o
../src/addon.cc:3:23: fatal error: secp256k1.h: No such file or directory
compilation terminated.
secp256k1.target.mk:143: recipe for target 'Release/obj.target/secp256k1/src/addon.o' failed
make: *** [Release/obj.target/secp256k1/src/addon.o] Error 1
make: Leaving directory '/home/user/code/tmp/node/ecc/node_modules/secp256k1/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.1-gentoo
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/code/tmp/node/ecc/node_modules/secp256k1
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

npm ERR! Linux 4.2.1-gentoo
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "rebuild"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@2.0.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@2.0.0 rebuild script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/code/tmp/node/ecc/node_modules/secp256k1/npm-debug.log
npm ERR! Linux 4.2.1-gentoo
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "secp256k1"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! secp256k1@2.0.0 install: `npm run rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@2.0.0 install script 'npm run rebuild'.
npm ERR! This is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/code/tmp/node/ecc/npm-debug.log
```

**Comment by fanatid** [comment]
I have same error. 2.0.0 package not contain folder src/secp256k1-src

**Comment by fanatid** [comment]
v2.0.1 published
