### ISSUE TITLE
Error with node-gyp rebuild in El Capitan

### ISSUE THREAD

**Issue by dcosta72** [cryptocoinjs/secp256k1-node#48]
I updated all the tools: node/npm/xcode. Cleared caches. When doing "npm install secp256k1", I get this:
# 

npm install  secp256k1

> secp256k1@2.0.2 install /<path>/node_modules/secp256k1
> npm run rebuild
> 
> secp256k1@2.0.2 rebuild /<path>/node_modules/secp256k1
> node-gyp rebuild

2015-11-10 15:47:14.023 xcodebuild[3179:48262] [MT] PluginLoading: Required plug-in compatibility UUID 7265231C-39B4-402C-89E1-16167C4CC990 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/SparkInspectorXcodePlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
  CXX(target) Release/obj.target/secp256k1/src/addon.o
  CXX(target) Release/obj.target/secp256k1/src/secretkey.o
  CXX(target) Release/obj.target/secp256k1/src/publickey.o
../src/publickey.cc:143:8: error: no member named 'unique_ptr' in namespace 'std'
  std::unique_ptr<secp256k1_pubkey[]> public_keys(new secp256k1_pubkey[buffers->Length()]);

``` ^
../src/publickey.cc:143:19: error: unexpected type name 'secp256k1_pubkey': expected expression
  std::unique_ptr<secp256k1_pubkey[]> public_keys(new secp256k1_pubkey[buffers->Length()]);
                  ^
../src/publickey.cc:143:36: error: expected expression
  std::unique_ptr<secp256k1_pubkey[]> public_keys(new secp256k1_pubkey[buffers->Length()]);
                                   ^
../src/publickey.cc:143:39: error: use of undeclared identifier 'public_keys'
  std::unique_ptr<secp256k1_pubkey[]> public_keys(new secp256k1_pubkey[buffers->Length()]);
                                      ^
../src/publickey.cc:144:8: error: no member named 'unique_ptr' in namespace 'std'
  std::unique_ptr<secp256k1_pubkey*[]> ins(new secp256k1_pubkey*[buffers->Length()]);
  ~~~~~^
../src/publickey.cc:144:19: error: unexpected type name 'secp256k1_pubkey': expected expression
  std::unique_ptr<secp256k1_pubkey*[]> ins(new secp256k1_pubkey*[buffers->Length()]);
                  ^
../src/publickey.cc:144:38: error: expected body of lambda expression
  std::unique_ptr<secp256k1_pubkey*[]> ins(new secp256k1_pubkey*[buffers->Length()]);
                                     ^
../src/publickey.cc:144:40: error: use of undeclared identifier 'ins'; did you mean 'int'?
  std::unique_ptr<secp256k1_pubkey*[]> ins(new secp256k1_pubkey*[buffers->Length()]);
                                       ^
../src/publickey.cc:152:50: error: use of undeclared identifier 'public_keys'
    if (secp256k1_ec_pubkey_parse(secp256k1ctx, &public_keys[i], input, inputlen) == 0) {
                                                 ^
../src/publickey.cc:156:5: error: use of undeclared identifier 'ins'; did you mean 'int'?
    ins[i] = &public_keys[i];
    ^~~
    int
../src/publickey.cc:156:12: error: expected unqualified-id
    ins[i] = &public_keys[i];
           ^
../src/publickey.cc:160:58: error: use of undeclared identifier 'ins'
  if (secp256k1_ec_pubkey_combine(secp256k1ctx, &pubkey, ins.get(), buffers->Length()) == 0) {
                                                         ^
12 errors generated.
make: *** [Release/obj.target/secp256k1/src/publickey.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /<path>/node_modules/secp256k1
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "rebuild"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@2.0.2 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@2.0.2 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /<path>/node_modules/secp256k1/npm-debug.log
npm WARN ENOENT ENOENT: no such file or directory, open '/<path>/package.json'
npm WARN EPACKAGEJSON webexperience No description
npm WARN EPACKAGEJSON webexperience No repository field.
npm WARN EPACKAGEJSON webexperience No README data
npm WARN EPACKAGEJSON webexperience No license field.
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "secp256k1"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! secp256k1@2.0.2 install: `npm run rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@2.0.2 install script 'npm run rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /<path>/npm-debug.log
================================================================


Any ideas? I know there's been issues on other platforms and it's been resolved, but doesn't seem to work on El Capitan....
```

**Comment by fanatid** [comment]
Can try to build module from repository with changed binding.gyp?

```
       'OS=="mac"', {
          "libraries": [
            "-L/usr/local/lib"
          ]
      }
replace to
       'OS=="mac"', {
          "libraries": [
            "-L/usr/local/lib"
          ],
          "xcode_settings": {
            "OTHER_CPLUSPLUSFLAGS" : [ "-std=c++0x" ],
          }
      }
```

**Comment by dcosta72** [comment]
same issue I'm afraid...

**Comment by claudiosdc** [comment]
I have successfully built the package on Mac OS X 10.11.1 with Xcode 7.1.1. by replacing the current 'OS=="mac"' entry of the binding.gyp file with the following:

```
  [
   'OS=="mac"', {
      "libraries": [
        "-L/usr/local/lib"
      ],
      "xcode_settings": {
        "MACOSX_DEPLOYMENT_TARGET": '10.7',
        "OTHER_CPLUSPLUSFLAGS": [
          '-stdlib=libc++'
        ]
      }
  }],
```

**Comment by fanatid** [comment]
Nice! Do you want make a PR?
