### ISSUE TITLE
build Killed on ubuntu 15.10 while "npm install"-ing

### ISSUE THREAD

**Issue by jesuscript** [cryptocoinjs/secp256k1-node#62]
``` bash
# npm install secp256k1@2.0.7

> secp256k1@2.0.7 install /root/trac-gateway/node_modules/secp256k1
> npm run rebuild


> secp256k1@2.0.7 rebuild /root/trac-gateway/node_modules/secp256k1
> node-gyp rebuild

make: Entering directory '/root/trac-gateway/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/src/addon.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
secp256k1.target.mk:143: recipe for target 'Release/obj.target/secp256k1/src/addon.o' failed
make: *** [Release/obj.target/secp256k1/src/addon.o] Error 4
make: Leaving directory '/root/trac-gateway/node_modules/secp256k1/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.2.0-16-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/trac-gateway/node_modules/secp256k1
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "rebuild"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@2.0.7 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@2.0.7 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/trac-gateway/node_modules/secp256k1/npm-debug.log
npm WARN EPACKAGEJSON trac-gateway No description
npm WARN EPACKAGEJSON trac-gateway No repository field.
npm WARN EPACKAGEJSON trac-gateway No license field.
npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "secp256k1@2.0.7"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! secp256k1@2.0.7 install: `npm run rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the secp256k1@2.0.7 install script 'npm run rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/trac-gateway/npm-debug.log
```

**Comment by wanderer** [comment]
Most likely a memory issue. Try clang

```
sudo apt-get update
sudo apt-get install clang
export CXX=clang++
npm install --clang=1
```

**Comment by jesuscript** [comment]
Right on the money! Compiling on a bigger machine (1gb RAM instead of 512mb) or using clang `CXX=clang++ npm install` builds successfully.

**Comment by wanderer** [comment]
awesome!

**Comment by jesuscript** [comment]
oddly this problem also happens (even with clang) on the first `npm install` on a new system. Consequent installs work fine.

```
 CXX=clang++ npm install
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json @ No license field.

> secp256k1@2.0.8 install /root/trac-gateway/node_modules/ethereumjs-util/node_modules/secp256k1
> npm run rebuild

-
> secp256k1@2.0.8 rebuild /root/trac-gateway/node_modules/ethereumjs-util/node_modules/secp256k1
> node-gyp rebuild

make: Entering directory '/root/trac-gateway/node_modules/ethereumjs-util/node_modules/secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/src/addon.o
clang: warning: optimization flag '-fno-tree-vrp' is not supported
clang: warning: argument unused during compilation: '-fno-tree-vrp'
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'?
      [-Wunknown-warning-option]
In file included from ../src/addon.cc:1:
In file included from /root/.node-gyp/0.12.9/src/node.h:61:
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:590:54: warning: unused parameter 'source' [-Wunused-parameter]
  V8_INLINE static void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:591:53: warning: unused parameter 'dest' [-Wunused-parameter]
                             NonCopyablePersistent* dest) {
                                                    ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:610:54: warning: unused parameter 'source' [-Wunused-parameter]
  static V8_INLINE void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:611:50: warning: unused parameter 'dest' [-Wunused-parameter]
                             CopyablePersistent* dest) {
                                                 ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:20: warning: unused parameter 'isolate' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:52: warning: unused parameter 'name' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                                                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4686:51: warning: unused parameter 'string' [-Wunused-parameter]
  virtual void VisitExternalString(Handle<String> string) {}
                                                  ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4696:57: warning: unused parameter 'value' [-Wunused-parameter]
  virtual void VisitPersistentHandle(Persistent<Value>* value,
                                                        ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4697:47: warning: unused parameter 'class_id' [-Wunused-parameter]
                                     uint16_t class_id) {}
                                              ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:5651:55: warning: unused parameter 'isolate' [-Wunused-parameter]
  V8_INLINE static void CheckInitialized(v8::Isolate* isolate) {
                                                      ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:6063:29: warning: unused parameter 'whatever' [-Wunused-parameter]
void ReturnValue<T>::Set(S* whatever) {
                            ^
In file included from ../src/addon.cc:2:
In file included from ../node_modules/nan/nan.h:150:
In file included from ../node_modules/nan/nan_callbacks.h:83:
../node_modules/nan/nan_callbacks_12_inl.h:89:22: warning: unused parameter 'whatever' [-Wunused-parameter]
  inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
                     ^
13 warnings generated.
  CXX(target) Release/obj.target/secp256k1/src/secretkey.o
clang: warning: optimization flag '-fno-tree-vrp' is not supported
clang: warning: argument unused during compilation: '-fno-tree-vrp'
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'?
      [-Wunknown-warning-option]
In file included from ../src/secretkey.cc:1:
In file included from /root/.node-gyp/0.12.9/src/node.h:61:
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:590:54: warning: unused parameter 'source' [-Wunused-parameter]
  V8_INLINE static void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:591:53: warning: unused parameter 'dest' [-Wunused-parameter]
                             NonCopyablePersistent* dest) {
                                                    ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:610:54: warning: unused parameter 'source' [-Wunused-parameter]
  static V8_INLINE void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:611:50: warning: unused parameter 'dest' [-Wunused-parameter]
                             CopyablePersistent* dest) {
                                                 ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:20: warning: unused parameter 'isolate' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:52: warning: unused parameter 'name' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                                                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4686:51: warning: unused parameter 'string' [-Wunused-parameter]
  virtual void VisitExternalString(Handle<String> string) {}
                                                  ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4696:57: warning: unused parameter 'value' [-Wunused-parameter]
  virtual void VisitPersistentHandle(Persistent<Value>* value,
                                                        ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4697:47: warning: unused parameter 'class_id' [-Wunused-parameter]
                                     uint16_t class_id) {}
                                              ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:5651:55: warning: unused parameter 'isolate' [-Wunused-parameter]
  V8_INLINE static void CheckInitialized(v8::Isolate* isolate) {
                                                      ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:6063:29: warning: unused parameter 'whatever' [-Wunused-parameter]
void ReturnValue<T>::Set(S* whatever) {
                            ^
In file included from ../src/secretkey.cc:2:
In file included from ../node_modules/nan/nan.h:150:
In file included from ../node_modules/nan/nan_callbacks.h:83:
../node_modules/nan/nan_callbacks_12_inl.h:89:22: warning: unused parameter 'whatever' [-Wunused-parameter]
  inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
                     ^
13 warnings generated.
  CXX(target) Release/obj.target/secp256k1/src/publickey.o
clang: warning: optimization flag '-fno-tree-vrp' is not supported
clang: warning: argument unused during compilation: '-fno-tree-vrp'
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'?
      [-Wunknown-warning-option]
In file included from ../src/publickey.cc:2:
In file included from /root/.node-gyp/0.12.9/src/node.h:61:
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:590:54: warning: unused parameter 'source' [-Wunused-parameter]
  V8_INLINE static void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:591:53: warning: unused parameter 'dest' [-Wunused-parameter]
                             NonCopyablePersistent* dest) {
                                                    ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:610:54: warning: unused parameter 'source' [-Wunused-parameter]
  static V8_INLINE void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:611:50: warning: unused parameter 'dest' [-Wunused-parameter]
                             CopyablePersistent* dest) {
                                                 ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:20: warning: unused parameter 'isolate' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:52: warning: unused parameter 'name' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                                                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4686:51: warning: unused parameter 'string' [-Wunused-parameter]
  virtual void VisitExternalString(Handle<String> string) {}
                                                  ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4696:57: warning: unused parameter 'value' [-Wunused-parameter]
  virtual void VisitPersistentHandle(Persistent<Value>* value,
                                                        ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4697:47: warning: unused parameter 'class_id' [-Wunused-parameter]
                                     uint16_t class_id) {}
                                              ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:5651:55: warning: unused parameter 'isolate' [-Wunused-parameter]
  V8_INLINE static void CheckInitialized(v8::Isolate* isolate) {
                                                      ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:6063:29: warning: unused parameter 'whatever' [-Wunused-parameter]
void ReturnValue<T>::Set(S* whatever) {
                            ^
In file included from ../src/publickey.cc:3:
In file included from ../node_modules/nan/nan.h:150:
In file included from ../node_modules/nan/nan_callbacks.h:83:
../node_modules/nan/nan_callbacks_12_inl.h:89:22: warning: unused parameter 'whatever' [-Wunused-parameter]
  inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
                     ^
13 warnings generated.
  CXX(target) Release/obj.target/secp256k1/src/signature.o
clang: warning: optimization flag '-fno-tree-vrp' is not supported
clang: warning: argument unused during compilation: '-fno-tree-vrp'
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'?
      [-Wunknown-warning-option]
In file included from ../src/signature.cc:1:
In file included from /root/.node-gyp/0.12.9/src/node.h:61:
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:590:54: warning: unused parameter 'source' [-Wunused-parameter]
  V8_INLINE static void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:591:53: warning: unused parameter 'dest' [-Wunused-parameter]
                             NonCopyablePersistent* dest) {
                                                    ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:610:54: warning: unused parameter 'source' [-Wunused-parameter]
  static V8_INLINE void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:611:50: warning: unused parameter 'dest' [-Wunused-parameter]
                             CopyablePersistent* dest) {
                                                 ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:20: warning: unused parameter 'isolate' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:52: warning: unused parameter 'name' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                                                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4686:51: warning: unused parameter 'string' [-Wunused-parameter]
  virtual void VisitExternalString(Handle<String> string) {}
                                                  ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4696:57: warning: unused parameter 'value' [-Wunused-parameter]
  virtual void VisitPersistentHandle(Persistent<Value>* value,
                                                        ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4697:47: warning: unused parameter 'class_id' [-Wunused-parameter]
                                     uint16_t class_id) {}
                                              ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:5651:55: warning: unused parameter 'isolate' [-Wunused-parameter]
  V8_INLINE static void CheckInitialized(v8::Isolate* isolate) {
                                                      ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:6063:29: warning: unused parameter 'whatever' [-Wunused-parameter]
void ReturnValue<T>::Set(S* whatever) {
                            ^
In file included from ../src/signature.cc:2:
In file included from ../node_modules/nan/nan.h:150:
In file included from ../node_modules/nan/nan_callbacks.h:83:
../node_modules/nan/nan_callbacks_12_inl.h:89:22: warning: unused parameter 'whatever' [-Wunused-parameter]
  inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
                     ^
13 warnings generated.
  CXX(target) Release/obj.target/secp256k1/src/sign.o
clang: warning: optimization flag '-fno-tree-vrp' is not supported
clang: warning: argument unused during compilation: '-fno-tree-vrp'
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'?
      [-Wunknown-warning-option]
In file included from ../src/sign.cc:1:
In file included from /root/.node-gyp/0.12.9/src/node.h:61:
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:590:54: warning: unused parameter 'source' [-Wunused-parameter]
  V8_INLINE static void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:591:53: warning: unused parameter 'dest' [-Wunused-parameter]
                             NonCopyablePersistent* dest) {
                                                    ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:610:54: warning: unused parameter 'source' [-Wunused-parameter]
  static V8_INLINE void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:611:50: warning: unused parameter 'dest' [-Wunused-parameter]
                             CopyablePersistent* dest) {
                                                 ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:20: warning: unused parameter 'isolate' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:52: warning: unused parameter 'name' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                                                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4686:51: warning: unused parameter 'string' [-Wunused-parameter]
  virtual void VisitExternalString(Handle<String> string) {}
                                                  ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4696:57: warning: unused parameter 'value' [-Wunused-parameter]
  virtual void VisitPersistentHandle(Persistent<Value>* value,
                                                        ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4697:47: warning: unused parameter 'class_id' [-Wunused-parameter]
                                     uint16_t class_id) {}
                                              ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:5651:55: warning: unused parameter 'isolate' [-Wunused-parameter]
  V8_INLINE static void CheckInitialized(v8::Isolate* isolate) {
                                                      ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:6063:29: warning: unused parameter 'whatever' [-Wunused-parameter]
void ReturnValue<T>::Set(S* whatever) {
                            ^
In file included from ../src/sign.cc:2:
In file included from ../node_modules/nan/nan.h:150:
In file included from ../node_modules/nan/nan_callbacks.h:83:
../node_modules/nan/nan_callbacks_12_inl.h:89:22: warning: unused parameter 'whatever' [-Wunused-parameter]
  inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
                     ^
13 warnings generated.
  CXX(target) Release/obj.target/secp256k1/src/verify.o
clang: warning: optimization flag '-fno-tree-vrp' is not supported
clang: warning: argument unused during compilation: '-fno-tree-vrp'
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'?
      [-Wunknown-warning-option]
In file included from ../src/verify.cc:1:
In file included from /root/.node-gyp/0.12.9/src/node.h:61:
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:590:54: warning: unused parameter 'source' [-Wunused-parameter]
  V8_INLINE static void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:591:53: warning: unused parameter 'dest' [-Wunused-parameter]
                             NonCopyablePersistent* dest) {
                                                    ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:610:54: warning: unused parameter 'source' [-Wunused-parameter]
  static V8_INLINE void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:611:50: warning: unused parameter 'dest' [-Wunused-parameter]
                             CopyablePersistent* dest) {
                                                 ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:20: warning: unused parameter 'isolate' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:52: warning: unused parameter 'name' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                                                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4686:51: warning: unused parameter 'string' [-Wunused-parameter]
  virtual void VisitExternalString(Handle<String> string) {}
                                                  ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4696:57: warning: unused parameter 'value' [-Wunused-parameter]
  virtual void VisitPersistentHandle(Persistent<Value>* value,
                                                        ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4697:47: warning: unused parameter 'class_id' [-Wunused-parameter]
                                     uint16_t class_id) {}
                                              ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:5651:55: warning: unused parameter 'isolate' [-Wunused-parameter]
  V8_INLINE static void CheckInitialized(v8::Isolate* isolate) {
                                                      ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:6063:29: warning: unused parameter 'whatever' [-Wunused-parameter]
void ReturnValue<T>::Set(S* whatever) {
                            ^
In file included from ../src/verify.cc:2:
In file included from ../node_modules/nan/nan.h:150:
In file included from ../node_modules/nan/nan_callbacks.h:83:
../node_modules/nan/nan_callbacks_12_inl.h:89:22: warning: unused parameter 'whatever' [-Wunused-parameter]
  inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
                     ^
13 warnings generated.
  CXX(target) Release/obj.target/secp256k1/src/recover.o
clang: warning: optimization flag '-fno-tree-vrp' is not supported
clang: warning: argument unused during compilation: '-fno-tree-vrp'
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'?
      [-Wunknown-warning-option]
In file included from ../src/recover.cc:1:
In file included from /root/.node-gyp/0.12.9/src/node.h:61:
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:590:54: warning: unused parameter 'source' [-Wunused-parameter]
  V8_INLINE static void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:591:53: warning: unused parameter 'dest' [-Wunused-parameter]
                             NonCopyablePersistent* dest) {
                                                    ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:610:54: warning: unused parameter 'source' [-Wunused-parameter]
  static V8_INLINE void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:611:50: warning: unused parameter 'dest' [-Wunused-parameter]
                             CopyablePersistent* dest) {
                                                 ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:20: warning: unused parameter 'isolate' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:52: warning: unused parameter 'name' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                                                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4686:51: warning: unused parameter 'string' [-Wunused-parameter]
  virtual void VisitExternalString(Handle<String> string) {}
                                                  ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4696:57: warning: unused parameter 'value' [-Wunused-parameter]
  virtual void VisitPersistentHandle(Persistent<Value>* value,
                                                        ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4697:47: warning: unused parameter 'class_id' [-Wunused-parameter]
                                     uint16_t class_id) {}
                                              ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:5651:55: warning: unused parameter 'isolate' [-Wunused-parameter]
  V8_INLINE static void CheckInitialized(v8::Isolate* isolate) {
                                                      ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:6063:29: warning: unused parameter 'whatever' [-Wunused-parameter]
void ReturnValue<T>::Set(S* whatever) {
                            ^
In file included from ../src/recover.cc:2:
In file included from ../node_modules/nan/nan.h:150:
In file included from ../node_modules/nan/nan_callbacks.h:83:
../node_modules/nan/nan_callbacks_12_inl.h:89:22: warning: unused parameter 'whatever' [-Wunused-parameter]
  inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
                     ^
13 warnings generated.
  CXX(target) Release/obj.target/secp256k1/src/ecdh.o
clang: warning: optimization flag '-fno-tree-vrp' is not supported
clang: warning: argument unused during compilation: '-fno-tree-vrp'
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'?
      [-Wunknown-warning-option]
In file included from ../src/ecdh.cc:1:
In file included from /root/.node-gyp/0.12.9/src/node.h:61:
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:590:54: warning: unused parameter 'source' [-Wunused-parameter]
  V8_INLINE static void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:591:53: warning: unused parameter 'dest' [-Wunused-parameter]
                             NonCopyablePersistent* dest) {
                                                    ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:610:54: warning: unused parameter 'source' [-Wunused-parameter]
  static V8_INLINE void Copy(const Persistent<S, M>& source,
                                                     ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:611:50: warning: unused parameter 'dest' [-Wunused-parameter]
                             CopyablePersistent* dest) {
                                                 ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:20: warning: unused parameter 'isolate' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:3823:52: warning: unused parameter 'name' [-Wunused-parameter]
      v8::Isolate* isolate, v8::Handle<v8::String> name) {
                                                   ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4686:51: warning: unused parameter 'string' [-Wunused-parameter]
  virtual void VisitExternalString(Handle<String> string) {}
                                                  ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4696:57: warning: unused parameter 'value' [-Wunused-parameter]
  virtual void VisitPersistentHandle(Persistent<Value>* value,
                                                        ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:4697:47: warning: unused parameter 'class_id' [-Wunused-parameter]
                                     uint16_t class_id) {}
                                              ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:5651:55: warning: unused parameter 'isolate' [-Wunused-parameter]
  V8_INLINE static void CheckInitialized(v8::Isolate* isolate) {
                                                      ^
/root/.node-gyp/0.12.9/deps/v8/include/v8.h:6063:29: warning: unused parameter 'whatever' [-Wunused-parameter]
void ReturnValue<T>::Set(S* whatever) {
                            ^
In file included from ../src/ecdh.cc:2:
In file included from ../node_modules/nan/nan.h:150:
In file included from ../node_modules/nan/nan_callbacks.h:83:
../node_modules/nan/nan_callbacks_12_inl.h:89:22: warning: unused parameter 'whatever' [-Wunused-parameter]
  inline void Set(S *whatever) { TYPE_CHECK(S*, v8::Primitive); }
                     ^
13 warnings generated.
  CC(target) Release/obj.target/secp256k1/src/secp256k1-src/src/secp256k1.o
Killed
root@trac:~/trac-gateway#   CC(target) Release/obj.target/secp256k1/src/secp256k1-src/contrib/lax_der_privatekey_parsing.o
  SOLINK_MODULE(target) Release/obj.target/secp256k1.node
  COPY Release/secp256k1.node
make: Leaving directory '/root/trac-gateway/node_modules/ethereumjs-util/node_modules/secp256k1/build'
```

**Comment by fanatid** [comment]
please reopen if issue is still actual
