### ISSUE TITLE
Mac OS X 10.10: Build Error

### ISSUE THREAD

**Issue by Latrasis** [cryptocoinjs/secp256k1-node#7]
Getting An Error on Build:

``` bash
CXX(target) Release/obj.target/secp256k1/secp256k1.o
../secp256k1.cc:5:10: fatal error: './secp256k1-src/include/secp256k1.h' file not found
#include "./secp256k1-src/include/secp256k1.h"
         ^
1 error generated.
make: *** [Release/obj.target/secp256k1/secp256k1.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
```

**Comment by wanderer** [comment]
are you installing this from npm or directly from git?

**Comment by Latrasis** [comment]
from npm: 2.1.17 and node: v0.10.35. OSX: 10.10.2

**Comment by wanderer** [comment]
I can't produce this yet.

**Comment by mvayngrib** [comment]
@wanderer i get something similar when cloning from git and installing (works when installed from npm as a dep): 
OSX 10.12.3
node 6.5.0
npm 3.10.3

let me know if there's any other information i can provide that could be helpful. Thanks!

```sh
> secp256k1@3.2.5 install /Users/tenaciousmv/Code/secp256k1-node
> prebuild-install || node-gyp rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."

prebuild-install info begin Prebuild-install version 2.1.1
prebuild-install info install installing inside prebuild-install directory, skipping download.
(node:24986) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
(node:24986) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
  CXX(target) Release/obj.target/secp256k1/src/addon.o
../src/addon.cc:3:10: fatal error: 'secp256k1.h' file not found
#include <secp256k1.h>
         ^
1 error generated.
make: *** [Release/obj.target/secp256k1/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/tenaciousmv/Code/secp256k1-node
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
Secp256k1 bindings compilation fail. Pure JS implementation will be used.
secp256k1@3.2.5 /Users/tenaciousmv/Code/secp256k1-node
```

**Comment by fanatid** [comment]
@mvayngrib you should clone repo with `--recursive`:
`git clone git@github.com:cryptocoinjs/secp256k1-node.git --recursive`

**Comment by mvayngrib** [comment]
@fanatid awesome, that did it, thanks! I see now that I missed the git submodule piece in the README, my bad.
