### ISSUE TITLE
On Windows, `npm rebuild` works, but executing `npm install` breaks the build

### ISSUE THREAD

**Issue by kripod** [cryptocoinjs/secp256k1-node#89]
I have OpenSSL installed at `C:/OpenSSL-Win64/`. When I install anything using `npm install`, the secp256k1 build gets broken:

```
>npm i

> secp256k1@2.0.10 install D:\Development\Projects\new-project\node_modules\secp256k1
> npm run rebuild


> secp256k1@2.0.10 rebuild D:\Development\Projects\new-project\node_modules\secp256k1
> node-gyp rebuild


D:\Development\Projects\new-project\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
'.' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to './utils/has_lib.sh gmpxx && ./utils/has_lib.sh gmp' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Development\Projects\new-project\node_modules\secp256k1
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! secp256k1@2.0.10 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@2.0.10 rebuild script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the secp256k1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs secp256k1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls secp256k1
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Development\Projects\new-project\node_modules\secp256k1\npm-debug.log
npm WARN install:secp256k1@2.0.10 secp256k1@2.0.10 install: `npm run rebuild`
npm WARN install:secp256k1@2.0.10 Exit status 1
```

But if I execute `npm rebuild`, everything becomes fine again:

```
>npm rebuild

> eccrypto@1.0.3 install D:\Development\Projects\new-project\node_modules\eccrypto
> node-gyp rebuild || exit 0


D:\Development\Projects\new-project\node_modules\eccrypto>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  ecdh.cc
  win_delay_load_hook.c
     Creating library D:\Development\Projects\new-project\node_modules\eccrypto\build\Release\ecdh.lib and object D:\Development\Projects\new-project
  \node_modules\eccrypto\build\Release\ecdh.exp
  Generating code
  Finished generating code
  ecdh.vcxproj -> D:\Development\Projects\new-project\node_modules\eccrypto\build\Release\\ecdh.node
eccrypto@1.0.3 D:\Development\Projects\new-project\node_modules\eccrypto
nan@2.3.5 D:\Development\Projects\new-project\node_modules\nan
```

**Comment by mattmezza** [comment]
Same here, I don't know what to do... Did you solve it?

**Comment by kripod** [comment]
No, I didn't.

**Comment by mattmezza** [comment]
I got it working by installing Visual Studio (during installation choose modify and install C++) and Windows sdk 8.1.

**Comment by kripod** [comment]
Doesn't it break eventually?

**Comment by mattmezza** [comment]
no, it installs... I am going to try to use it

**Comment by kgapos** [comment]
This is a major issue for me, installing visual studio is not an option for me. I don't presume there's a chance of fixing this in a couple days? My hackathon depends on it :(

**Comment by mattmezza** [comment]
I got it working but I have installed Visual Studio and done a couple of things I forgot about. Good luck for your hackaton @kgapos 👍

**Comment by kripod** [comment]
@kgapos May I suggest using the great [elliptic](https://github.com/indutny/elliptic) library of Fedor Indutny as an alternative? [Eccrypto](https://github.com/bitchan/eccrypto) may also be a good choice for performing crypto operations in plain javascript.

**Comment by fanatid** [comment]
When bindings fail library will be use `elliptic` by Fedor, but you also can use embedded implementation (which little faster).
For building library on windows please check notes in README: https://github.com/cryptocoinjs/secp256k1-node/tree/d96965d40369a70ac255413b4f9474dc4ea7ffa4#windows
