### ISSUE TITLE
gmp not found

### ISSUE THREAD

**Issue by kumavis** [cryptocoinjs/secp256k1-node#9]
gmp not found, though i have it brew installed

```
╰─○ npm i
npm WARN package.json semaphore@1.0.1 No repository field.
npm http GET https://registry.npmjs.org/secp256k1/0.0.13
npm http 304 https://registry.npmjs.org/secp256k1/0.0.13
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan

> secp256k1@0.0.13 install /Users/kumavis/Development/Node/node-ethereum/node_modules/secp256k1
> node-gyp rebuild

  CXX(target) Release/obj.target/secp256k1/secp256k1.o
../secp256k1.cc:488:54: warning: variable 'privKey' is uninitialized when used here [-Wuninitialized]
  int results = secp256k1_ec_privkey_export(sk_data, privKey, &pk_len, compressed);
                                                     ^~~~~~~
../secp256k1.cc:486:25: note: initialize the variable 'privKey' to silence this warning
  unsigned char *privKey;
                        ^
                         = NULL
1 warning generated.
  CC(target) Release/obj.target/secp256k1/secp256k1-src/src/secp256k1.o
In file included from ../secp256k1-src/src/secp256k1.c:12:
In file included from ../secp256k1-src/src/num_impl.h:14:
In file included from ../secp256k1-src/src/num.h:17:
../secp256k1-src/src/num_gmp.h:10:10: fatal error: 'gmp.h' file not found
#include <gmp.h>
         ^
1 error generated.
make: *** [Release/obj.target/secp256k1/secp256k1-src/src/secp256k1.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/share/npm/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/share/npm/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/kumavis/Development/Node/node-ethereum/node_modules/secp256k1
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by wanderer** [comment]
if i had to guess [this](https://github.com/wanderer/secp256k1-node/blob/master/binding.gyp#L61-L63) flag might be wrong. What compiler & version are you using?

**Comment by kumavis** [comment]
Uninstalling `gmp` worked

```
╭─{👺 } kumavis in ~/Development/Node/node-ethereum on (develop✱)
╰─○ brew uninstall gmp
Uninstalling /usr/local/Cellar/gmp/6.0.0a...
╭─{👺 } kumavis in ~/Development/Node/node-ethereum on (develop✱)
╰─○ npm i
npm WARN package.json semaphore@1.0.1 No repository field.
npm http GET https://registry.npmjs.org/secp256k1/0.0.13
npm http 304 https://registry.npmjs.org/secp256k1/0.0.13
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan

> secp256k1@0.0.13 install /Users/kumavis/Development/Node/node-ethereum/node_modules/secp256k1
> node-gyp rebuild

  CXX(target) Release/obj.target/secp256k1/secp256k1.o
../secp256k1.cc:488:54: warning: variable 'privKey' is uninitialized when used here [-Wuninitialized]
  int results = secp256k1_ec_privkey_export(sk_data, privKey, &pk_len, compressed);
                                                     ^~~~~~~
../secp256k1.cc:486:25: note: initialize the variable 'privKey' to silence this warning
  unsigned char *privKey;
                        ^
                         = NULL
1 warning generated.
  CC(target) Release/obj.target/secp256k1/secp256k1-src/src/secp256k1.o
In file included from ../secp256k1-src/src/secp256k1.c:13:
../secp256k1-src/src/field_impl.h:42:12: warning: unused function 'secp256k1_fe_set_hex' [-Wunused-function]
static int secp256k1_fe_set_hex(secp256k1_fe_t *r, const char *a, int alen) {
           ^
In file included from ../secp256k1-src/src/secp256k1.c:13:
In file included from ../secp256k1-src/src/field_impl.h:19:
../secp256k1-src/src/field_5x52_impl.h:55:13: warning: unused function 'secp256k1_fe_verify' [-Wunused-function]
static void secp256k1_fe_verify(const secp256k1_fe_t *a) {
            ^
In file included from ../secp256k1-src/src/secp256k1.c:15:
../secp256k1-src/src/group_impl.h:16:13: warning: unused function 'secp256k1_ge_set_infinity' [-Wunused-function]
static void secp256k1_ge_set_infinity(secp256k1_ge_t *r) {
            ^
../secp256k1-src/src/group_impl.h:30:13: warning: unused function 'secp256k1_ge_neg' [-Wunused-function]
static void secp256k1_ge_neg(secp256k1_ge_t *r, const secp256k1_ge_t *a) {
            ^
../secp256k1-src/src/group_impl.h:124:13: warning: unused function 'secp256k1_gej_set_xy' [-Wunused-function]
static void secp256k1_gej_set_xy(secp256k1_gej_t *r, const secp256k1_fe_t *x, const secp256k1_fe_t *y) {
            ^
../secp256k1-src/src/group_impl.h:409:13: warning: unused function 'secp256k1_gej_get_hex' [-Wunused-function]
static void secp256k1_gej_get_hex(char *r, int *rlen, const secp256k1_gej_t *a) {
            ^
In file included from ../secp256k1-src/src/secp256k1.c:14:
In file included from ../secp256k1-src/src/scalar_impl.h:20:
../secp256k1-src/src/scalar_4x64_impl.h:400:13: warning: unused function 'secp256k1_scalar_split_128' [-Wunused-function]
static void secp256k1_scalar_split_128(secp256k1_scalar_t *r1, secp256k1_scalar_t *r2, const secp256k1_scalar_t *a) {
            ^
In file included from ../secp256k1-src/src/secp256k1.c:15:
../secp256k1-src/src/group_impl.h:188:12: warning: unused function 'secp256k1_gej_is_valid_var' [-Wunused-function]
static int secp256k1_gej_is_valid_var(const secp256k1_gej_t *a) {
           ^
In file included from ../secp256k1-src/src/secp256k1.c:18:
In file included from ../secp256k1-src/src/ecdsa_impl.h:16:
../secp256k1-src/src/ecdsa.h:13:13: warning: unused function 'secp256k1_ecsda_start' [-Wunused-function]
static void secp256k1_ecsda_start(void);
            ^
In file included from ../secp256k1-src/src/secp256k1.c:18:
../secp256k1-src/src/ecdsa_impl.h:221:13: warning: unused function 'secp256k1_ecdsa_sig_set_rs' [-Wunused-function]
static void secp256k1_ecdsa_sig_set_rs(secp256k1_ecdsa_sig_t *sig, const secp256k1_scalar_t *r, const secp256k1_scalar_t *s) {
            ^
10 warnings generated.
  SOLINK_MODULE(target) Release/secp256k1.node
  SOLINK_MODULE(target) Release/secp256k1.node: Finished
secp256k1@0.0.13 node_modules/secp256k1
├── bindings@1.2.1
└── nan@1.5.1
```

**Comment by kumavis** [comment]
I guess I'll leave it open as its a legitimate issue.

**Comment by adv0r** [comment]
I am having similar issue building geth frontier 1.0.0
http://pastebin.ca/3082012

**Comment by wanderer** [comment]
node -v v0.10.35 is not supported any more, feel free to reopen if this happens on a later version
